version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  app:
    build: .
    volumes:
      - ../app:/code/
    depends_on:
      - db
    tty: true

volumes:
  postgres_data:
